export const DUMMY_DATA = [
  {
    id: 1,
    name: "Apple",
    category: "Fruits",
    price: "$1",
    quantity: 50,
    value: "$60.00",
    isProductDiable: false,
  },
  {
    id: 2,
    name: "Carrot",
    category: "Vegetables",
    price: "$1",
    quantity: 100,
    value: "$80.00",
    isProductDiable: false,
  },
  {
    id: 3,
    name: "Chicken Breast",
    category: "Meat",
    price: "$5.00",
    quantity: 20,
    value: "$100.00",
    isProductDiable: false,
  },
  {
    id: 4,
    name: "Milk",
    category: "Dairy",
    price: "$1",
    quantity: 30,
    value: "$45.00",
    isProductDiable: false,
  },
  {
    id: 5,
    name: "Bread",
    category: "Bakery",
    price: "$1",
    quantity: 40,
    value: "$100.00",
    isProductDiable: false,
  },
];
